FROM python:3.13.7-alpine3.21

WORKDIR /app

# Instalar dependências do sistema
RUN apk add --no-cache gcc musl-dev

# Instalar dependências Python
RUN pip install --no-cache-dir pyzmq msgpack

COPY ../servidor.py .

CMD ["python", "servidor.py"]
